In [1]:
import numpy as np
a = np.array([1,2,3])

In [2]:
print(a)

[1 2 3]


In [6]:
b = np.array([(2,5,7), (5,3,9), (6,8,9)])

In [7]:
print(b)

[[2 5 7]
 [5 3 9]
 [6 8 9]]


In [8]:
c=np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
